version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            virtualenv .venv
            source .venv/bin/activate
            make init
      - run:
          name: run tests
          command: |
            source .venv/bin/activate
            make test
      - run:
          name: lint
          command: |
            source .venv/bin/activate
            make lint
