version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            virtualenv .venv
            virtualenv -p python3 .venv3
            source .venv/bin/activate && make init
            source .venv3/bin/activate && make init
      - run:
          name: run tests
          command: |
            source .venv/bin/activate && make test
            source .venv3/bin/activate && make test
      - run:
          name: lint
          command: |
            source .venv/bin/activate && make lint
            source .venv3/bin/activate && make lint
